FROM node:12.2.0-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

# RUN npm install -g @angular/cli@7.0.2

CMD npm run ng serve -- --liveReload=false --watch=false --host=0.0.0.0 --disable-host-check --prod